name: Pull Request

on:
  pull_request:
    branches: [master]

jobs:
  verify:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['20.x']
        os: [ubuntu-latest]
    env:
      CI: 1
      NPM_TOKEN: ${{ secrets.NPM_RO_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --immutable

      - name: Verify
        run: make verify
